# Generated by Django 5.2 on 2025-05-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techjays', '0002_uploadedfile_delete_techjaysdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
