# Generated by Django 5.2 on 2025-05-15 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techjays', '0004_remove_uploadedfile_text_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chathistory',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='message',
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='role',
        ),
        migrations.AddField(
            model_name='chathistory',
            name='name',
            field=models.CharField(default='New Chat', max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='chat_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='techjays.chathistory'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='session_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chat_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='techjays.chathistory')),
            ],
        ),
    ]
