# Generated by Django 5.2 on 2025-05-16 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techjays', '0005_rename_timestamp_chathistory_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='message',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='role',
        ),
        migrations.AddField(
            model_name='chathistory',
            name='document_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='name',
            field=models.CharField(default='New Chat', max_length=200),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='chat_history',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='techjays.chathistory'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='uploaded_files/'),
        ),
    ]
