# Generated by Django 5.2 on 2025-05-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techjays', '0006_rename_message_chatmessage_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='document_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='name',
            field=models.CharField(default='Chat', max_length=100),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='session_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
